# Trabalho_T1/Dockerfile.dev
FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --upgrade pip setuptools wheel \
    && pip install -r requirements.txt \
    || (pip install --upgrade pip setuptools wheel && pip install -r requirements.txt)

# Copiamos tudo, mas em dev você pode usar volume para hot-reload
COPY . /app/

# Mantém usuário padrão (dev)
EXPOSE 8000

ENV DEBUG=1 \
    USE_GUNICORN=0 \
    DJANGO_SETTINGS_MODULE=config.settings \
    PYTHONPATH=/app

ENTRYPOINT ["/app/entrypoint.sh"]
