# Trabalho_T1/docker-compose.prod.yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trabalho_t1
    ports:
      - "8000:8000"
    restart: always
    environment:
      DEBUG: "0"
      USE_GUNICORN: "1"
      SECRET_KEY: "${SECRET_KEY:-change-me}"
      ALLOWED_HOSTS: "*,34.227.111.218,localhost"
      # Para DB externo (opcional): DATABASE_URL=postgres://user:pass@host:5432/dbname
      # Para idioma/timezone, se quiser:
      # DJANGO_SETTINGS_MODULE: config.settings
